unit test.ddl.identity;

interface

uses
  DUnitX.TestFramework;

type
  [TestFixture]
  TTestDDLIdentity = class
  public
    [Test]
    procedure TestIdentity_PostgreSQL_GeneratesExpected;
    [Test]
    procedure TestIdentity_MSSQL_GeneratesExpected;
    [Test]
    procedure TestIdentity_MySQL_GeneratesExpected;
    [Test]
    procedure TestIdentity_Firebird_GeneratesExpected;
    [Test]
    procedure TestIdentity_SQLite_GeneratesExpected;
    [Test]
    procedure TestIdentity_OnNonNumeric_RaisesException;
    [Test]
    procedure TestIdentity_InAlterTableAdd_GeneratesExpected;
  end;

implementation

uses
  System.SysUtils,
  FluentSQL,
  FluentSQL.Interfaces;

{ TTestDDLIdentity }

procedure TTestDDLIdentity.TestIdentity_PostgreSQL_GeneratesExpected;
var
  LSql: string;
begin
  LSql := FluentSQL.Schema(dbnPostgreSQL).CreateTable('USERS')
    .ColumnInteger('ID').PrimaryKey.Identity
    .AsString;
  Assert.AreEqual('CREATE TABLE "USERS" ("ID" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY)', LSql);
end;

procedure TTestDDLIdentity.TestIdentity_MSSQL_GeneratesExpected;
var
  LSql: string;
begin
  LSql := FluentSQL.Schema(dbnMSSQL).CreateTable('USERS')
    .ColumnInteger('ID').PrimaryKey.Identity
    .AsString;
  Assert.AreEqual('CREATE TABLE [USERS] ([ID] INT IDENTITY(1,1) PRIMARY KEY)', LSql);
end;

procedure TTestDDLIdentity.TestIdentity_MySQL_GeneratesExpected;
var
  LSql: string;
begin
  LSql := FluentSQL.Schema(dbnMySQL).CreateTable('USERS')
    .ColumnInteger('ID').PrimaryKey.Identity
    .AsString;
  Assert.AreEqual('CREATE TABLE `USERS` (`ID` INT AUTO_INCREMENT PRIMARY KEY)', LSql);
end;

procedure TTestDDLIdentity.TestIdentity_Firebird_GeneratesExpected;
var
  LSql: string;
begin
  LSql := FluentSQL.Schema(dbnFirebird).CreateTable('USERS')
    .ColumnInteger('ID').PrimaryKey.Identity
    .AsString;
  Assert.AreEqual('CREATE TABLE "USERS" ("ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)', LSql);
end;

procedure TTestDDLIdentity.TestIdentity_SQLite_GeneratesExpected;
var
  LSql: string;
begin
  LSql := FluentSQL.Schema(dbnSQLite).CreateTable('USERS')
    .ColumnInteger('ID').PrimaryKey.Identity
    .AsString;
  Assert.AreEqual('CREATE TABLE `USERS` (`ID` INTEGER PRIMARY KEY AUTOINCREMENT)', LSql);
end;

procedure TTestDDLIdentity.TestIdentity_OnNonNumeric_RaisesException;
begin
  Assert.WillRaise(
    procedure
    begin
      FluentSQL.Schema(dbnPostgreSQL).CreateTable('T')
        .ColumnVarChar('NAME', 100).Identity
        .AsString;
    end,
    EArgumentException);
end;

procedure TTestDDLIdentity.TestIdentity_InAlterTableAdd_GeneratesExpected;
var
  LSql: string;
begin
  LSql := FluentSQL.Schema(dbnPostgreSQL).AlterTableAdd('USERS')
    .ColumnInteger('NEW_REF').Identity
    .AsString;
  Assert.AreEqual('ALTER TABLE "USERS" ADD "NEW_REF" INTEGER GENERATED ALWAYS AS IDENTITY', LSql);
end;

initialization
  TDUnitX.RegisterTestFixture(TTestDDLIdentity);

end.
