unit test.ddl.oracle;

interface

uses
  DUnitX.TestFramework;

type
  [TestFixture]
  TTestDDLOracle = class
  public
    [Test]
    procedure TestTruncateTable_Oracle_SingleTable_GeneratesExpected;
    [Test]
    procedure TestIdentity_Oracle_Always_GeneratesExpected;
    [Test]
    procedure TestIdentity_Oracle_ByDefault_GeneratesExpected;
    [Test]
    procedure TestIdentity_AlterTableAlter_Oracle_GeneratesExpected;
  end;

implementation

uses
  System.SysUtils,
  FluentSQL,
  FluentSQL.Interfaces;

{ TTestDDLOracle }

procedure TTestDDLOracle.TestTruncateTable_Oracle_SingleTable_GeneratesExpected;
var
  LSql: string;
begin
  LSql := FluentSQL.Schema(dbnOracle).TruncateTable('CLIENTES').AsString;
  Assert.AreEqual('TRUNCATE TABLE "CLIENTES"', LSql);
end;

procedure TTestDDLOracle.TestIdentity_Oracle_Always_GeneratesExpected;
var
  LSql: string;
begin
  LSql := FluentSQL.Schema(dbnOracle).Table('LOGS').Create
    .ColumnBigInt('ID').Identity(disAlways)
    .AsString;
  Assert.AreEqual('CREATE TABLE "LOGS" ("ID" NUMBER(19) GENERATED ALWAYS AS IDENTITY)', LSql);
end;

procedure TTestDDLOracle.TestIdentity_Oracle_ByDefault_GeneratesExpected;
var
  LSql: string;
begin
  LSql := FluentSQL.Schema(dbnOracle).Table('LOGS').Create
    .ColumnBigInt('ID').Identity(disByDefault)
    .AsString;
  Assert.AreEqual('CREATE TABLE "LOGS" ("ID" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY)', LSql);
end;

procedure TTestDDLOracle.TestIdentity_AlterTableAlter_Oracle_GeneratesExpected;
var
  LSql: string;
begin
  LSql := FluentSQL.Schema(dbnOracle).Table('LOGS').Alter.Column('ID')
    .Identity(disAlways)
    .AsString;
  Assert.AreEqual('ALTER TABLE "LOGS" MODIFY "ID" GENERATED ALWAYS AS IDENTITY', LSql);
end;

initialization
  TDUnitX.RegisterTestFixture(TTestDDLOracle);

end.
