{
  ------------------------------------------------------------------------------
  FluentSQL
  Firebird DDL serialization driver.

  SPDX-License-Identifier: MIT
  Copyright (c) 2026 Ecosystem - Innovative Tools for Delphi Development

  Licensed under the MIT License.
  See the LICENSE file in the project root for full license information.
  ------------------------------------------------------------------------------
}

unit FluentSQL.DDL.Serialize.Firebird;

interface

{$ifdef fpc}
  {$mode delphi}{$H+}
{$endif}

uses
  SysUtils,
  FluentSQL.Interfaces,
  FluentSQL.DDL.SerializeAbstract;

type
  TFluentDDLSerializerFirebird = class(TFluentDDLSerializeAbstract)
  protected
    function MapLogicalType(const AType: TDDLLogicalType; const AArg: Integer = 0): string; override;
    function GetDialect: TFluentSQLDriver; override;
    function Quote(const AName: string): string; override;
    function GetComputedDefinition(const ACol: IFluentDDLColumn): string; override;
    function GetIdentityDefinition(const ACol: IFluentDDLColumn): string; override;
    function GetColumnComment(const ATable: string; const ACol: IFluentDDLColumn): string; override;
    function GetTableComment(const ATable: IFluentDDLTableDef): string; override;
  public
    function CreateTable(const ADef: IFluentDDLTableDef): string; override;
    function DropTable(const ADef: IFluentDDLDropTableDef): string; override;
    function AlterTableAddColumn(const ADef: IFluentDDLAlterTableAddColumnDef): string; override;
    function AlterTableDropColumn(const ADef: IFluentDDLAlterTableDropColumnDef): string; override;
    function AlterTableRenameColumn(const ADef: IFluentDDLAlterTableRenameColumnDef): string; override;
    function AlterTableRenameTable(const ADef: IFluentDDLAlterTableRenameTableDef): string; override;
    function AlterTableAlterColumn(const ADef: IFluentDDLAlterTableAlterColumnDef): string; override;
    function CreateIndex(const ADef: IFluentDDLCreateIndexDef): string; override;
    function DropIndex(const ADef: IFluentDDLDropIndexDef): string; override;
    function TruncateTable(const ADef: IFluentDDLTruncateTableDef): string; override;
    function CreateView(const ADef: IFluentDDLCreateViewDef): string; override;
    function DropView(const ADef: IFluentDDLDropViewDef): string; override;
    function CreateSequence(const ADef: IFluentDDLCreateSequenceDef): string; override;
    function DropSequence(const ADef: IFluentDDLDropSequenceDef): string; override;
    function AlterTableAddConstraint(const ADef: IFluentDDLAlterTableAddConstraintDef): string; override;
    function AlterTableDropConstraint(const ADef: IFluentDDLAlterTableDropConstraintDef): string; override;
    function CreateProcedure(const ADef: IFluentDDLProcedureDef): string; override;
    function DropProcedure(const ADef: IFluentDDLDropProcedureDef): string; override;
    function CreateTrigger(const ADef: IFluentDDLTriggerDef): string; override;
    function DropTrigger(const ADef: IFluentDDLDropTriggerDef): string; override;
    function ManageTrigger(const ADef: IFluentDDLTriggerManagementDef): string; override;
  end;

implementation

{ TFluentDDLSerializerFirebird }

function TFluentDDLSerializerFirebird.Quote(const AName: string): string;
begin
  if (AName = '') or (AName.StartsWith('"')) then
    Exit(AName);
  Result := '"' + AName + '"';
end;

function TFluentDDLSerializerFirebird.GetComputedDefinition(const ACol: IFluentDDLColumn): string;
begin
  Result := '';
  if ACol.ComputedExpression <> '' then
    Result := ' COMPUTED BY (' + ACol.ComputedExpression + ')';
end;

function TFluentDDLSerializerFirebird.GetIdentityDefinition(const ACol: IFluentDDLColumn): string;
begin
  Result := '';
  if ACol.IsIdentity then
  begin
    if ACol.IdentityScope = disAlways then
      Result := ' GENERATED ALWAYS AS IDENTITY'
    else
      Result := ' GENERATED BY DEFAULT AS IDENTITY';
  end;
end;

function TFluentDDLSerializerFirebird.GetColumnComment(const ATable: string; const ACol: IFluentDDLColumn): string;
begin
  Result := '';
  if ACol.Description <> '' then
    Result := '; ' + 'COMMENT ON COLUMN ' + Quote(ATable) + '.' + Quote(ACol.Name) + ' IS ' + QuotedStr(ACol.Description);
end;

function TFluentDDLSerializerFirebird.GetTableComment(const ATable: IFluentDDLTableDef): string;
begin
  Result := '';
  if ATable.Description <> '' then
    Result := '; ' + 'COMMENT ON TABLE ' + Quote(ATable.TableName) + ' IS ' + QuotedStr(ATable.Description);
end;

function TFluentDDLSerializerFirebird.GetDialect: TFluentSQLDriver;
begin
  Result := dbnFirebird;
end;

function TFluentDDLSerializerFirebird.MapLogicalType(const AType: TDDLLogicalType; const AArg: Integer = 0): string;
begin
  case AType of
    dltInteger:
      Result := 'INTEGER';
    dltBigInt:
      Result := 'BIGINT';
    dltVarChar:
      Result := 'VARCHAR(' + IntToStr(AArg) + ')';
    dltBoolean:
      Result := 'BOOLEAN';
    dltDate:
      Result := 'DATE';
    dltDateTime:
      Result := 'TIMESTAMP';
    dltLongText:
      Result := 'BLOB SUB_TYPE 1';
    dltBlob:
      Result := 'BLOB SUB_TYPE 0';
    dltGuid:
      Result := 'CHAR(16) CHARACTER SET OCTETS';
  else
    raise ENotSupportedException.Create('DDL: unknown logical type');
  end;
end;

function TFluentDDLSerializerFirebird.CreateTable(const ADef: IFluentDDLTableDef): string;
var
  LI: Integer;
begin
  if not Assigned(ADef) then
    Exit('');
  if ADef.GetColumnCount <= 0 then
    raise EArgumentException.Create('DDL: empty column list');

  Result := 'CREATE TABLE ' + Quote(ADef.TableName) + ' (' + GetColumnDefinitionList(ADef) + GetTableConstraintList(ADef) + ')';
  
  Result := Result + GetTableComment(ADef);
  for LI := 0 to ADef.GetColumnCount - 1 do
    Result := Result + GetColumnComment(ADef.TableName, ADef.GetColumn(LI));
end;

function TFluentDDLSerializerFirebird.DropTable(const ADef: IFluentDDLDropTableDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if Trim(ADef.TableName) = '' then
    raise EArgumentException.Create('DDL: table name is required');

  if ADef.GetIfExists then
    raise ENotSupportedException.Create(
      'DDL DROP TABLE: IF EXISTS is not emitted for Firebird in this build; use CreateFluentDDLDropTable(...).AsString ' +
      'without IfExists, or compose dialect-specific SQL in the application (e.g. Firebird 4+).')
  else
    Result := 'DROP TABLE ' + Quote(ADef.TableName);
end;

function TFluentDDLSerializerFirebird.AlterTableAddColumn(const ADef: IFluentDDLAlterTableAddColumnDef): string;
var
  LCol: IFluentDDLColumn;
begin
  if not Assigned(ADef) then
    Exit('');
  LCol := ADef.Column;
  if not Assigned(LCol) then
    raise EArgumentException.Create('DDL ALTER TABLE: a column definition is required');

  Result := 'ALTER TABLE ' + Quote(ADef.TableName) + ' ADD ' + GetColumnDefinition(LCol);
  Result := Result + GetColumnComment(ADef.TableName, LCol);
end;

function TFluentDDLSerializerFirebird.AlterTableDropColumn(const ADef: IFluentDDLAlterTableDropColumnDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if Trim(ADef.ColumnName) = '' then
    raise EArgumentException.Create('DDL ALTER TABLE DROP COLUMN: a column target is required');

  Result := 'ALTER TABLE ' + Quote(ADef.TableName) + ' DROP ' + Quote(ADef.ColumnName);
end;

function TFluentDDLSerializerFirebird.AlterTableRenameColumn(const ADef: IFluentDDLAlterTableRenameColumnDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  Result := 'ALTER TABLE ' + Quote(ADef.TableName) + ' ALTER ' + Quote(ADef.OldColumnName) + ' TO ' + Quote(ADef.NewColumnName);
end;

function TFluentDDLSerializerFirebird.AlterTableRenameTable(const ADef: IFluentDDLAlterTableRenameTableDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  Result := 'ALTER TABLE ' + Quote(ADef.OldTableName) + ' TO ' + Quote(ADef.NewTableName);
end;

function TFluentDDLSerializerFirebird.AlterTableAlterColumn(const ADef: IFluentDDLAlterTableAlterColumnDef): string;
begin
  if not Assigned(ADef) then
    Exit('');

  if ADef.NullabilityChanged then
     raise ENotSupportedException.Create('DDL Firebird: nullability change is not supported for ALTER COLUMN (ADR-050).');

  if ADef.TypeChanged then
    Result := 'ALTER TABLE ' + Quote(ADef.TableName) + ' ALTER ' + Quote(ADef.ColumnName) + ' TYPE ' + MapLogicalType(ADef.LogicalType, ADef.TypeArg)
  else if ADef.DefaultDropped then
    Result := 'ALTER TABLE ' + Quote(ADef.TableName) + ' ALTER ' + Quote(ADef.ColumnName) + ' DROP DEFAULT'
  else if ADef.DefaultSet then
    Result := 'ALTER TABLE ' + Quote(ADef.TableName) + ' ALTER ' + Quote(ADef.ColumnName) + ' SET DEFAULT ' + GetLiteralValue(ADef.DefaultValue, ADef.LogicalType)
  else if ADef.IdentityChanged then
  begin
    if ADef.IdentityScope = disByDefault then
      Result := 'ALTER TABLE ' + Quote(ADef.TableName) + ' ALTER ' + Quote(ADef.ColumnName) + ' SET GENERATED BY DEFAULT'
    else
      Result := 'ALTER TABLE ' + Quote(ADef.TableName) + ' ALTER ' + Quote(ADef.ColumnName) + ' SET GENERATED ALWAYS';
  end
  else
    raise EArgumentException.Create('DDL ALTER TABLE ALTER COLUMN: at least one change is required.');
end;

function TFluentDDLSerializerFirebird.CreateIndex(const ADef: IFluentDDLCreateIndexDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if ADef.IsUnique then
    Result := 'CREATE UNIQUE INDEX ' + Quote(ADef.IndexName) + ' ON ' + Quote(ADef.TableName) + ' (' + GetColumnNameList(ADef) + ')'
  else
    Result := 'CREATE INDEX ' + Quote(ADef.IndexName) + ' ON ' + Quote(ADef.TableName) + ' (' + GetColumnNameList(ADef) + ')';
end;

function TFluentDDLSerializerFirebird.DropIndex(const ADef: IFluentDDLDropIndexDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if ADef.GetConcurrently then
    raise ENotSupportedException.Create(
      'DDL DROP INDEX CONCURRENTLY (ESP-027) is not supported for Firebird; only PostgreSQL maps CONCURRENTLY (ADR-027).');
  if Trim(ADef.GetTableName) <> '' then
    raise ENotSupportedException.Create('DDL DROP INDEX: table name is not supported for Firebird (DROP INDEX ... ON ...).');

  if ADef.GetIfExists then
    Result := 'DROP INDEX IF EXISTS ' + Quote(ADef.IndexName)
  else
    Result := 'DROP INDEX ' + Quote(ADef.IndexName);
end;

function TFluentDDLSerializerFirebird.TruncateTable(const ADef: IFluentDDLTruncateTableDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if ADef.GetRestartIdentity or ADef.GetCascade then
    raise ENotSupportedException.Create(
      'DDL TRUNCATE TABLE: RESTART IDENTITY and CASCADE are PostgreSQL-only options in this vertical (ESP-029 / ADR-029).');
  Result := 'TRUNCATE TABLE ' + Quote(ADef.TableName);
end;

function TFluentDDLSerializerFirebird.CreateView(const ADef: IFluentDDLCreateViewDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if ADef.OrReplace then
    Result := 'CREATE OR ALTER VIEW ' + Quote(ADef.ViewName) + ' AS ' + ADef.Query.AsString
  else
    Result := 'CREATE VIEW ' + Quote(ADef.ViewName) + ' AS ' + ADef.Query.AsString;
end;

function TFluentDDLSerializerFirebird.DropView(const ADef: IFluentDDLDropViewDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if ADef.IfExists then
    Result := 'DROP VIEW IF EXISTS ' + Quote(ADef.ViewName)
  else
    Result := 'DROP VIEW ' + Quote(ADef.ViewName);
end;

function TFluentDDLSerializerFirebird.CreateSequence(const ADef: IFluentDDLCreateSequenceDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  Result := 'CREATE SEQUENCE ' + Quote(ADef.SequenceName);
end;

function TFluentDDLSerializerFirebird.DropSequence(const ADef: IFluentDDLDropSequenceDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if ADef.IfExists then
    raise ENotSupportedException.Create('DDL Firebird: DROP SEQUENCE IF EXISTS is not supported (ADR-054).');

  Result := 'DROP SEQUENCE ' + Quote(ADef.SequenceName);
end;

function TFluentDDLSerializerFirebird.AlterTableAddConstraint(const ADef: IFluentDDLAlterTableAddConstraintDef): string;
begin
  Result := inherited AlterTableAddConstraint(ADef);
end;

function TFluentDDLSerializerFirebird.AlterTableDropConstraint(const ADef: IFluentDDLAlterTableDropConstraintDef): string;
begin
  Result := inherited AlterTableDropConstraint(ADef);
end;

function TFluentDDLSerializerFirebird.CreateProcedure(const ADef: IFluentDDLProcedureDef): string;
begin
  if not Assigned(ADef) then
    Exit('');

  if ADef.OrReplace then
    Result := 'CREATE OR ALTER PROCEDURE ' + Quote(ADef.ProcedureName)
  else
    Result := 'CREATE PROCEDURE ' + Quote(ADef.ProcedureName);

  if ADef.Params <> '' then
    Result := Result + ' (' + ADef.Params + ')';

  Result := Result + ' AS ' + ADef.Body;
end;

function TFluentDDLSerializerFirebird.DropProcedure(const ADef: IFluentDDLDropProcedureDef): string;
begin
  if not Assigned(ADef) then
    Exit('');

  if ADef.IfExists then
    Result := 'DROP PROCEDURE IF EXISTS ' + Quote(ADef.ProcedureName)
  else
    Result := 'DROP PROCEDURE ' + Quote(ADef.ProcedureName);
end;

function TFluentDDLSerializerFirebird.CreateTrigger(const ADef: IFluentDDLTriggerDef): string;
var
  LTime, LEvent: string;
begin
  if not Assigned(ADef) then
    Exit('');

  LTime := 'AFTER';
  if ADef.Time = ttBefore then LTime := 'BEFORE';

  case ADef.Event of
    teInsert: LEvent := 'INSERT';
    teUpdate: LEvent := 'UPDATE';
    teDelete: LEvent := 'DELETE';
  else
    LEvent := 'INSERT';
  end;

  Result := 'CREATE TRIGGER ' + Quote(ADef.TriggerName) + ' FOR ' + Quote(ADef.TableName) +
            ' ' + LTime + ' ' + LEvent + ' AS ' + ADef.Body;
end;

function TFluentDDLSerializerFirebird.DropTrigger(const ADef: IFluentDDLDropTriggerDef): string;
begin
  if not Assigned(ADef) then
    Exit('');

  if ADef.IfExists then
    Result := 'DROP TRIGGER IF EXISTS ' + Quote(ADef.TriggerName)
  else
    Result := 'DROP TRIGGER ' + Quote(ADef.TriggerName);
end;

function TFluentDDLSerializerFirebird.ManageTrigger(const ADef: IFluentDDLTriggerManagementDef): string;
begin
  if not Assigned(ADef) then
    Exit('');

  if ADef.Enabled then
    Result := 'ALTER TRIGGER ' + Quote(ADef.TriggerName) + ' ACTIVE'
  else
    Result := 'ALTER TRIGGER ' + Quote(ADef.TriggerName) + ' INACTIVE';
end;

end.
