{
  ------------------------------------------------------------------------------
  FluentSQL
  Database-agnostic fluent SQL/MQL script generation library for Delphi and Lazarus.

  SPDX-License-Identifier: MIT
  Copyright (c) 2025-2026 Isaque Pinheiro

  Licensed under the MIT License.
  See the LICENSE file in the project root for full license information.
  ------------------------------------------------------------------------------
}

unit FluentSQL.DDL.Serialize.Firebird;

interface

{$ifdef fpc}
  {$mode delphi}{$H+}
{$endif}

uses
  SysUtils,
  FluentSQL.Interfaces,
  FluentSQL.DDL.SerializeAbstract;

type
  TFluentDDLSerializerFirebird = class(TFluentDDLSerializeAbstract)
  protected
    function MapLogicalType(const AType: TDDLLogicalType; const AArg: Integer = 0;
      const APrecision: Integer = 0; const AScale: Integer = 0): string; override;
    function GetDialect: TFluentSQLDriver; override;
    function Quote(const AName: string): string; override;
    function GetComputedDefinition(const ACol: IFluentDDLColumn): string; override;
    function GetIdentityDefinition(const ACol: IFluentDDLColumn): string; override;
    function GetColumnComment(const ATable: string; const ACol: IFluentDDLColumn): string; override;
    function GetTableComment(const ATable: IFluentDDLTableDef): string; override;
  public
    function CreateTable(const ADef: IFluentDDLTableDef): string; override;
    function DropTable(const ADef: IFluentDDLDropTableDef): string; override;
    function AlterTableAddColumn(const ADef: IFluentDDLAlterTableAddColumnDef): string; override;
    function AlterTableDropColumn(const ADef: IFluentDDLAlterTableDropColumnDef): string; override;
    function AlterTableRenameColumn(const ADef: IFluentDDLAlterTableRenameColumnDef): string; override;
    function AlterTableRenameTable(const ADef: IFluentDDLAlterTableRenameTableDef): string; override;
    function AlterTableAlterColumn(const ADef: IFluentDDLAlterTableAlterColumnDef): string; override;
    function CreateIndex(const ADef: IFluentDDLCreateIndexDef): string; override;
    function DropIndex(const ADef: IFluentDDLDropIndexDef): string; override;
    function TruncateTable(const ADef: IFluentDDLTruncateTableDef): string; override;
    function CreateView(const ADef: IFluentDDLCreateViewDef): string; override;
    function DropView(const ADef: IFluentDDLDropViewDef): string; override;
    function CreateSequence(const ADef: IFluentDDLCreateSequenceDef): string; override;
    function DropSequence(const ADef: IFluentDDLDropSequenceDef): string; override;
    function AlterTableAddConstraint(const ADef: IFluentDDLAlterTableAddConstraintDef): string; override;
    function AlterTableDropConstraint(const ADef: IFluentDDLAlterTableDropConstraintDef): string; override;
    function CreateProcedure(const ADef: IFluentDDLProcedureDef): string; override;
    function DropProcedure(const ADef: IFluentDDLDropProcedureDef): string; override;
    function CreateTrigger(const ADef: IFluentDDLTriggerDef): string; override;
    function DropTrigger(const ADef: IFluentDDLDropTriggerDef): string; override;
    function ManageTrigger(const ADef: IFluentDDLTriggerManagementDef): string; override;
    function CreateFunction(const ADef: IFluentDDLFunctionDef): string; override;
    function DropFunction(const ADef: IFluentDDLDropFunctionDef): string; override;
    function CreateSchema(const ADef: IFluentSQLSchemaDef): string; override;
    function DropSchema(const ADef: IFluentSQLSchemaDef): string; override;
  end;

implementation

{ TFluentDDLSerializerFirebird }

function TFluentDDLSerializerFirebird.Quote(const AName: string): string;
begin
  if (AName = '') or (AName.StartsWith('"')) then
    Exit(AName);
  Result := '"' + AName + '"';
end;

function TFluentDDLSerializerFirebird.GetComputedDefinition(const ACol: IFluentDDLColumn): string;
begin
  Result := '';
  if ACol.ComputedExpression <> '' then
    Result := ' COMPUTED BY (' + ACol.ComputedExpression + ')';
end;

function TFluentDDLSerializerFirebird.GetIdentityDefinition(const ACol: IFluentDDLColumn): string;
begin
  Result := '';
  if ACol.IsIdentity then
  begin
    if ACol.IdentityScope = disAlways then
      Result := ' GENERATED ALWAYS AS IDENTITY'
    else
      Result := ' GENERATED BY DEFAULT AS IDENTITY';
  end;
end;

function TFluentDDLSerializerFirebird.GetColumnComment(const ATable: string; const ACol: IFluentDDLColumn): string;
begin
  Result := '';
  if ACol.Description <> '' then
    Result := '; ' + 'COMMENT ON COLUMN ' + Quote(ATable) + '.' + Quote(ACol.Name) + ' IS ' + QuotedStr(ACol.Description);
end;

function TFluentDDLSerializerFirebird.GetTableComment(const ATable: IFluentDDLTableDef): string;
begin
  Result := '';
  if ATable.Description <> '' then
    Result := '; ' + 'COMMENT ON TABLE ' + Quote(ATable.TableName) + ' IS ' + QuotedStr(ATable.Description);
end;

function TFluentDDLSerializerFirebird.GetDialect: TFluentSQLDriver;
begin
  Result := dbnFirebird;
end;

function TFluentDDLSerializerFirebird.MapLogicalType(const AType: TDDLLogicalType; const AArg: Integer;
  const APrecision: Integer; const AScale: Integer): string;
begin
  case AType of
    dltInteger: Result := 'INTEGER';
    dltBigInt: Result := 'BIGINT';
    dltVarChar: Result := 'VARCHAR(' + IntToStr(AArg) + ')';
    dltBoolean: Result := 'BOOLEAN';
    dltDate: Result := 'DATE';
    dltDateTime: Result := 'TIMESTAMP';
    dltLongText: Result := 'BLOB SUB_TYPE 1';
    dltBlob: Result := 'BLOB SUB_TYPE 0';
    dltGuid: Result := 'CHAR(16) CHARACTER SET OCTETS';
    dltNumeric: Result := MapNumeric('NUMERIC', APrecision, AScale);
    dltDecimal: Result := MapNumeric('DECIMAL', APrecision, AScale);
  else
    raise ENotSupportedException.Create('DDL: unknown logical type');
  end;
end;

function TFluentDDLSerializerFirebird.CreateTable(const ADef: IFluentDDLTableDef): string;
var
  LI: Integer;
begin
  if not Assigned(ADef) then
    Exit('');
  if ADef.GetColumnCount <= 0 then
    raise EArgumentException.Create('DDL: empty column list');

  Result := 'CREATE TABLE ' + Quote(ADef.TableName) + ' (' + GetColumnDefinitionList(ADef) + GetTableConstraintList(ADef) + ')';
  
  Result := Result + GetTableComment(ADef);
  for LI := 0 to ADef.GetColumnCount - 1 do
    Result := Result + GetColumnComment(ADef.TableName, ADef.GetColumn(LI));
end;

function TFluentDDLSerializerFirebird.DropTable(const ADef: IFluentDDLDropTableDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if Trim(ADef.TableName) = '' then
    raise EArgumentException.Create('DDL: table name is required');

  if ADef.GetIfExists then
    raise ENotSupportedException.Create(
      'DDL DROP TABLE: IF EXISTS is not emitted for Firebird in this build; use CreateFluentDDLDropTable(...).AsString ' +
      'without IfExists, or compose dialect-specific SQL in the application (e.g. Firebird 4+).')
  else
    Result := 'DROP TABLE ' + Quote(ADef.TableName);
end;

function TFluentDDLSerializerFirebird.AlterTableAddColumn(const ADef: IFluentDDLAlterTableAddColumnDef): string;
var
  LCol: IFluentDDLColumn;
begin
  if not Assigned(ADef) then
    Exit('');
  LCol := ADef.Column;
  if not Assigned(LCol) then
    raise EArgumentException.Create('DDL ALTER TABLE: a column definition is required');

  Result := 'ALTER TABLE ' + Quote(ADef.TableName) + ' ADD ' + GetColumnDefinition(LCol);
  Result := Result + GetColumnComment(ADef.TableName, LCol);
end;

function TFluentDDLSerializerFirebird.AlterTableDropColumn(const ADef: IFluentDDLAlterTableDropColumnDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if Trim(ADef.ColumnName) = '' then
    raise EArgumentException.Create('DDL ALTER TABLE DROP COLUMN: a column target is required');

  Result := 'ALTER TABLE ' + Quote(ADef.TableName) + ' DROP ' + Quote(ADef.ColumnName);
end;

function TFluentDDLSerializerFirebird.AlterTableRenameColumn(const ADef: IFluentDDLAlterTableRenameColumnDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  Result := 'ALTER TABLE ' + Quote(ADef.TableName) + ' ALTER ' + Quote(ADef.OldColumnName) + ' TO ' + Quote(ADef.NewColumnName);
end;

// T35: o Firebird nao tem DDL de renomear TABELA. Nao e que a forma emitida
// estivesse errada e outra estivesse certa - nao existe forma. Medido em
// firebirdsql/firebird:5.0.4 (ENGINE_VERSION perguntado ao motor = 5.0.4):
//   ALTER TABLE "TAB_A" TO "TAB_B";         -104 -Token unknown ... -TO
//   ALTER TABLE "TAB_A" RENAME TO "TAB_B";  -104 -Token unknown ... -RENAME
//   RENAME TABLE "TAB_A" TO "TAB_B";        -104 -Token unknown ... -RENAME
// O 'ALTER TABLE t ALTER col TO col2' logo acima, para COLUNA, esta certo e foi
// confirmado no mesmo motor; e so o analogo de tabela que o dialeto nao tem.
// Recusar segue a convencao que este arquivo ja aplica ao que o Firebird nao
// expressa (DropTable/IfExists, CreateSchema, DropSchema, sequencias).
function TFluentDDLSerializerFirebird.AlterTableRenameTable(const ADef: IFluentDDLAlterTableRenameTableDef): string;
begin
  raise ENotSupportedException.Create(
    'DDL Firebird: renaming a table is not supported; Firebird has no table-rename DDL ' +
    '(measured on 5.0.4: ALTER TABLE ... TO ..., ALTER TABLE ... RENAME TO ... and RENAME TABLE ... ' +
    'all fail with -104 Token unknown). Recreate the table and migrate the rows in the application.');
end;

function TFluentDDLSerializerFirebird.AlterTableAlterColumn(const ADef: IFluentDDLAlterTableAlterColumnDef): string;
begin
  if not Assigned(ADef) then
    Exit('');

  if ADef.NullabilityChanged then
     raise ENotSupportedException.Create('DDL Firebird: nullability change is not supported for ALTER COLUMN (ADR-050).');

  if ADef.TypeChanged then
    Result := 'ALTER TABLE ' + Quote(ADef.TableName) + ' ALTER ' + Quote(ADef.ColumnName) + ' TYPE ' + MapLogicalType(ADef.LogicalType, ADef.TypeArg, ADef.Precision, ADef.Scale)
  else if ADef.DefaultDropped then
    Result := 'ALTER TABLE ' + Quote(ADef.TableName) + ' ALTER ' + Quote(ADef.ColumnName) + ' DROP DEFAULT'
  else if ADef.DefaultSet then
    Result := 'ALTER TABLE ' + Quote(ADef.TableName) + ' ALTER ' + Quote(ADef.ColumnName) + ' SET DEFAULT ' + GetLiteralValue(ADef.DefaultValue, ADef.LogicalType)
  else if ADef.IdentityChanged then
  begin
    if ADef.IdentityScope = disByDefault then
      Result := 'ALTER TABLE ' + Quote(ADef.TableName) + ' ALTER ' + Quote(ADef.ColumnName) + ' SET GENERATED BY DEFAULT'
    else
      Result := 'ALTER TABLE ' + Quote(ADef.TableName) + ' ALTER ' + Quote(ADef.ColumnName) + ' SET GENERATED ALWAYS';
  end
  else
    raise EArgumentException.Create('DDL ALTER TABLE ALTER COLUMN: at least one change is required.');
end;

function TFluentDDLSerializerFirebird.CreateIndex(const ADef: IFluentDDLCreateIndexDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if ADef.IsUnique then
    Result := 'CREATE UNIQUE INDEX ' + Quote(ADef.IndexName) + ' ON ' + Quote(ADef.TableName) + ' (' + GetColumnNameList(ADef) + ')'
  else
    Result := 'CREATE INDEX ' + Quote(ADef.IndexName) + ' ON ' + Quote(ADef.TableName) + ' (' + GetColumnNameList(ADef) + ')';
end;

function TFluentDDLSerializerFirebird.DropIndex(const ADef: IFluentDDLDropIndexDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if ADef.GetConcurrently then
    raise ENotSupportedException.Create(
      'DDL DROP INDEX CONCURRENTLY (ESP-027) is not supported for Firebird; only PostgreSQL maps CONCURRENTLY (ADR-027).');
  if Trim(ADef.GetTableName) <> '' then
    raise ENotSupportedException.Create('DDL DROP INDEX: table name is not supported for Firebird (DROP INDEX ... ON ...).');

  // T35: medido em firebirdsql/firebird:5.0.4 - 'DROP INDEX IF EXISTS "X"'
  // devolve -104 -Token unknown - line 1, column 15 -EXISTS, e devolve o MESMO
  // erro para indice existente e para indice ausente: e recusa de sintaxe, nao
  // de alvo. A forma nua executa (controle positivo: o indice sumiu de
  // RDB$INDICES) e sobre indice ausente devolve -607 "Index not found", que e o
  // que cabe a aplicacao tratar. Mesma regra que DropTable acima ja aplica ao
  // mesmo modificador neste dialeto.
  if ADef.GetIfExists then
    raise ENotSupportedException.Create(
      'DDL DROP INDEX: IF EXISTS is not emitted for Firebird in this build; Firebird 5.0 rejects it ' +
      '(-104 Token unknown - EXISTS). Drop the index unconditionally and handle -607 (Index not found) ' +
      'in the application.');

  Result := 'DROP INDEX ' + Quote(ADef.IndexName);
end;

function TFluentDDLSerializerFirebird.TruncateTable(const ADef: IFluentDDLTruncateTableDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if Length(ADef.TableNames) > 1 then
    raise ENotSupportedException.Create('DDL Firebird: multiple tables in a single TRUNCATE are not supported.');
  if ADef.RestartIdentity or ADef.ContinueIdentity or ADef.Cascade or (ADef.PartitionName <> '') then
    raise ENotSupportedException.Create('DDL Firebird: advanced TRUNCATE options (RESTART IDENTITY, CASCADE, PARTITION) are not supported.');

  Result := 'TRUNCATE TABLE ' + Quote(ADef.TableName);
end;

function TFluentDDLSerializerFirebird.CreateView(const ADef: IFluentDDLCreateViewDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if ADef.OrReplace then
    Result := 'CREATE OR ALTER VIEW ' + Quote(ADef.ViewName) + ' AS ' + ADef.Query.AsString
  else
    Result := 'CREATE VIEW ' + Quote(ADef.ViewName) + ' AS ' + ADef.Query.AsString;
end;

function TFluentDDLSerializerFirebird.DropView(const ADef: IFluentDDLDropViewDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if ADef.IfExists then
    Result := 'DROP VIEW IF EXISTS ' + Quote(ADef.ViewName)
  else
    Result := 'DROP VIEW ' + Quote(ADef.ViewName);
end;

function TFluentDDLSerializerFirebird.CreateSequence(const ADef: IFluentDDLCreateSequenceDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  Result := 'CREATE SEQUENCE ' + Quote(ADef.SequenceName);
end;

function TFluentDDLSerializerFirebird.DropSequence(const ADef: IFluentDDLDropSequenceDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if ADef.IfExists then
    raise ENotSupportedException.Create('DDL Firebird: DROP SEQUENCE IF EXISTS is not supported (ADR-054).');

  Result := 'DROP SEQUENCE ' + Quote(ADef.SequenceName);
end;

function TFluentDDLSerializerFirebird.AlterTableAddConstraint(const ADef: IFluentDDLAlterTableAddConstraintDef): string;
begin
  Result := inherited AlterTableAddConstraint(ADef);
end;

function TFluentDDLSerializerFirebird.AlterTableDropConstraint(const ADef: IFluentDDLAlterTableDropConstraintDef): string;
begin
  Result := inherited AlterTableDropConstraint(ADef);
end;

function TFluentDDLSerializerFirebird.CreateProcedure(const ADef: IFluentDDLProcedureDef): string;
begin
  if not Assigned(ADef) then
    Exit('');

  if ADef.OrReplace then
    Result := 'CREATE OR ALTER PROCEDURE ' + Quote(ADef.ProcedureName)
  else
    Result := 'CREATE PROCEDURE ' + Quote(ADef.ProcedureName);

  if ADef.Params <> '' then
    Result := Result + ' (' + ADef.Params + ')';

  Result := Result + ' AS ' + ADef.Body;
end;

function TFluentDDLSerializerFirebird.DropProcedure(const ADef: IFluentDDLDropProcedureDef): string;
begin
  if not Assigned(ADef) then
    Exit('');

  if ADef.IfExists then
    Result := 'DROP PROCEDURE IF EXISTS ' + Quote(ADef.ProcedureName)
  else
    Result := 'DROP PROCEDURE ' + Quote(ADef.ProcedureName);
end;

function TFluentDDLSerializerFirebird.CreateTrigger(const ADef: IFluentDDLTriggerDef): string;
var
  LTime, LEvent: string;
begin
  if not Assigned(ADef) then
    Exit('');

  LTime := 'AFTER';
  if ADef.Time = ttBefore then LTime := 'BEFORE';

  case ADef.Event of
    teInsert: LEvent := 'INSERT';
    teUpdate: LEvent := 'UPDATE';
    teDelete: LEvent := 'DELETE';
  else
    LEvent := 'INSERT';
  end;

  Result := 'CREATE TRIGGER ' + Quote(ADef.TriggerName) + ' FOR ' + Quote(ADef.TableName) +
            ' ' + LTime + ' ' + LEvent + ' AS ' + ADef.Body;
end;

function TFluentDDLSerializerFirebird.DropTrigger(const ADef: IFluentDDLDropTriggerDef): string;
begin
  if not Assigned(ADef) then
    Exit('');

  if ADef.IfExists then
    Result := 'DROP TRIGGER IF EXISTS ' + Quote(ADef.TriggerName)
  else
    Result := 'DROP TRIGGER ' + Quote(ADef.TriggerName);
end;

function TFluentDDLSerializerFirebird.ManageTrigger(const ADef: IFluentDDLTriggerManagementDef): string;
begin
  if not Assigned(ADef) then
    Exit('');

  if ADef.Enabled then
    Result := 'ALTER TRIGGER ' + Quote(ADef.TriggerName) + ' ACTIVE'
  else
    Result := 'ALTER TRIGGER ' + Quote(ADef.TriggerName) + ' INACTIVE';
end;

function TFluentDDLSerializerFirebird.CreateFunction(const ADef: IFluentDDLFunctionDef): string;
begin
  if not Assigned(ADef) then
    Exit('');

  if ADef.OrReplace then
    Result := 'CREATE OR ALTER FUNCTION ' + Quote(ADef.FunctionName)
  else
    Result := 'CREATE FUNCTION ' + Quote(ADef.FunctionName);

  if ADef.Params <> '' then
    Result := Result + ' (' + ADef.Params + ')';

  Result := Result + ' RETURNS ' + ADef.Returns + ' AS ' + ADef.Body;
end;

function TFluentDDLSerializerFirebird.DropFunction(const ADef: IFluentDDLDropFunctionDef): string;
begin
  if not Assigned(ADef) then
    Exit('');

  if ADef.IfExists then
    Result := 'DROP FUNCTION IF EXISTS ' + Quote(ADef.FunctionName)
  else
    Result := 'DROP FUNCTION ' + Quote(ADef.FunctionName);
end;

function TFluentDDLSerializerFirebird.CreateSchema(const ADef: IFluentSQLSchemaDef): string;
begin
  raise ENotSupportedException.Create('DDL Firebird: CREATE SCHEMA is not supported (ADR-075).');
end;

function TFluentDDLSerializerFirebird.DropSchema(const ADef: IFluentSQLSchemaDef): string;
begin
  raise ENotSupportedException.Create('DDL Firebird: DROP SCHEMA is not supported (ADR-075).');
end;

end.
