{
  ------------------------------------------------------------------------------
  FluentSQL
  PostgreSQL DDL serialization driver.

  SPDX-License-Identifier: MIT
  Copyright (c) 2026 Ecosystem - Innovative Tools for Delphi Development

  Licensed under the MIT License.
  See the LICENSE file in the project root for full license information.
  ------------------------------------------------------------------------------
}

unit FluentSQL.DDL.Serialize.PostgreSQL;

interface

{$ifdef fpc}
  {$mode delphi}{$H+}
{$endif}

uses
  SysUtils,
  Classes,
  FluentSQL.Interfaces,
  FluentSQL.DDL.SerializeAbstract;

type
  TFluentDDLSerializerPostgreSQL = class(TFluentDDLSerializeAbstract)
  protected
    function MapLogicalType(const AType: TDDLLogicalType; const AArg: Integer = 0;
      const APrecision: Integer = 0; const AScale: Integer = 0): string; override;
    function GetDialect: TFluentSQLDriver; override;
    function Quote(const AName: string): string; override;
    function GetComputedDefinition(const ACol: IFluentDDLColumn): string; override;
    function GetIdentityDefinition(const ACol: IFluentDDLColumn): string; override;
    function GetColumnComment(const ATable: string; const ACol: IFluentDDLColumn): string; override;
    function GetTableComment(const ATable: IFluentDDLTableDef): string; override;
  public
    function CreateTable(const ADef: IFluentDDLTableDef): string; override;
    function DropTable(const ADef: IFluentDDLDropTableDef): string; override;
    function AlterTableAddColumn(const ADef: IFluentDDLAlterTableAddColumnDef): string; override;
    function AlterTableDropColumn(const ADef: IFluentDDLAlterTableDropColumnDef): string; override;
    function AlterTableRenameColumn(const ADef: IFluentDDLAlterTableRenameColumnDef): string; override;
    function AlterTableAlterColumn(const ADef: IFluentDDLAlterTableAlterColumnDef): string; override;
    function CreateIndex(const ADef: IFluentDDLCreateIndexDef): string; override;
    function DropIndex(const ADef: IFluentDDLDropIndexDef): string; override;
    function TruncateTable(const ADef: IFluentDDLTruncateTableDef): string; override;
    function CreateView(const ADef: IFluentDDLCreateViewDef): string; override;
    function DropView(const ADef: IFluentDDLDropViewDef): string; override;
    function CreateSequence(const ADef: IFluentDDLCreateSequenceDef): string; override;
    function DropSequence(const ADef: IFluentDDLDropSequenceDef): string; override;
    function AlterTableAddConstraint(const ADef: IFluentDDLAlterTableAddConstraintDef): string; override;
    function AlterTableDropConstraint(const ADef: IFluentDDLAlterTableDropConstraintDef): string; override;
    function CreateProcedure(const ADef: IFluentDDLProcedureDef): string; override;
    function DropProcedure(const ADef: IFluentDDLDropProcedureDef): string; override;
    function CreateTrigger(const ADef: IFluentDDLTriggerDef): string; override;
    function DropTrigger(const ADef: IFluentDDLDropTriggerDef): string; override;
    function ManageTrigger(const ADef: IFluentDDLTriggerManagementDef): string; override;
    function CreateFunction(const ADef: IFluentDDLFunctionDef): string; override;
    function DropFunction(const ADef: IFluentDDLDropFunctionDef): string; override;
    function CreateSchema(const ADef: IFluentSQLSchemaDef): string; override;
    function DropSchema(const ADef: IFluentSQLSchemaDef): string; override;
  end;

implementation

{ TFluentDDLSerializerPostgreSQL }

function TFluentDDLSerializerPostgreSQL.GetDialect: TFluentSQLDriver;
begin
  Result := dbnPostgreSQL;
end;

function TFluentDDLSerializerPostgreSQL.Quote(const AName: string): string;
begin
  if (AName = '') or (AName.StartsWith('"')) then
    Exit(AName);
  Result := '"' + AName + '"';
end;

function TFluentDDLSerializerPostgreSQL.GetComputedDefinition(const ACol: IFluentDDLColumn): string;
begin
  Result := '';
  if ACol.ComputedExpression <> '' then
    Result := ' GENERATED ALWAYS AS (' + ACol.ComputedExpression + ') STORED';
end;

function TFluentDDLSerializerPostgreSQL.GetIdentityDefinition(const ACol: IFluentDDLColumn): string;
begin
  Result := '';
  if ACol.IsIdentity then
  begin
    if ACol.IdentityScope = disByDefault then
      Result := ' GENERATED BY DEFAULT AS IDENTITY'
    else
      Result := ' GENERATED ALWAYS AS IDENTITY';
  end;
end;

function TFluentDDLSerializerPostgreSQL.GetColumnComment(const ATable: string; const ACol: IFluentDDLColumn): string;
begin
  Result := '';
  if ACol.Description <> '' then
    Result := '; ' + 'COMMENT ON COLUMN ' + Quote(ATable) + '.' + Quote(ACol.Name) + ' IS ' + QuotedStr(ACol.Description);
end;

function TFluentDDLSerializerPostgreSQL.GetTableComment(const ATable: IFluentDDLTableDef): string;
begin
  Result := '';
  if ATable.Description <> '' then
    Result := '; ' + 'COMMENT ON TABLE ' + Quote(ATable.TableName) + ' IS ' + QuotedStr(ATable.Description);
end;

function TFluentDDLSerializerPostgreSQL.MapLogicalType(const AType: TDDLLogicalType; const AArg: Integer;
  const APrecision: Integer; const AScale: Integer): string;
begin
  case AType of
    dltInteger: Result := 'INTEGER';
    dltBigInt: Result := 'BIGINT';
    dltVarChar: Result := 'VARCHAR(' + IntToStr(AArg) + ')';
    dltBoolean: Result := 'BOOLEAN';
    dltDate: Result := 'DATE';
    dltDateTime: Result := 'TIMESTAMP';
    dltLongText: Result := 'TEXT';
    dltBlob: Result := 'BYTEA';
    dltGuid: Result := 'UUID';
    dltNumeric: Result := MapNumeric('NUMERIC', APrecision, AScale);
    dltDecimal: Result := MapNumeric('DECIMAL', APrecision, AScale);
  else
    raise ENotSupportedException.Create('DDL: unknown logical type');
  end;
end;

function TFluentDDLSerializerPostgreSQL.CreateTable(const ADef: IFluentDDLTableDef): string;
var
  LI: Integer;
begin
  if not Assigned(ADef) then
    Exit('');
  if ADef.GetColumnCount <= 0 then
    raise EArgumentException.Create('DDL: empty column list');

  Result := 'CREATE TABLE ' + Quote(ADef.TableName) + ' (' + GetColumnDefinitionList(ADef) + GetTableConstraintList(ADef) + ')';
  
  Result := Result + GetTableComment(ADef);
  for LI := 0 to ADef.GetColumnCount - 1 do
    Result := Result + GetColumnComment(ADef.TableName, ADef.GetColumn(LI));
end;

function TFluentDDLSerializerPostgreSQL.DropTable(const ADef: IFluentDDLDropTableDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if Trim(ADef.TableName) = '' then
    raise EArgumentException.Create('DDL: table name is required');

  if ADef.GetIfExists then
    Result := 'DROP TABLE IF EXISTS ' + Quote(ADef.TableName)
  else
    Result := 'DROP TABLE ' + Quote(ADef.TableName);
end;

function TFluentDDLSerializerPostgreSQL.AlterTableAddColumn(const ADef: IFluentDDLAlterTableAddColumnDef): string;
var
  LCol: IFluentDDLColumn;
begin
  if not Assigned(ADef) then
    Exit('');
  LCol := ADef.Column;
  if not Assigned(LCol) then
    raise EArgumentException.Create('DDL ALTER TABLE: a column definition is required');

  Result := 'ALTER TABLE ' + Quote(ADef.TableName) + ' ADD ' + GetColumnDefinition(LCol);
  Result := Result + GetColumnComment(ADef.TableName, LCol);
end;

function TFluentDDLSerializerPostgreSQL.AlterTableDropColumn(const ADef: IFluentDDLAlterTableDropColumnDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if Trim(ADef.ColumnName) = '' then
    raise EArgumentException.Create('DDL ALTER TABLE DROP COLUMN: a column target is required');

  Result := 'ALTER TABLE ' + Quote(ADef.TableName) + ' DROP COLUMN ' + Quote(ADef.ColumnName);
end;

function TFluentDDLSerializerPostgreSQL.AlterTableRenameColumn(const ADef: IFluentDDLAlterTableRenameColumnDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  Result := 'ALTER TABLE ' + Quote(ADef.TableName) + ' RENAME COLUMN ' + Quote(ADef.OldColumnName) + ' TO ' + Quote(ADef.NewColumnName);
end;

function TFluentDDLSerializerPostgreSQL.AlterTableAlterColumn(const ADef: IFluentDDLAlterTableAlterColumnDef): string;
var
  LBase: string;
  LParts: TStringList;
begin
  if not Assigned(ADef) then
    Exit('');

  LBase := 'ALTER TABLE ' + Quote(ADef.TableName);
  LParts := TStringList.Create;
  try
    if ADef.TypeChanged then
      LParts.Add('ALTER COLUMN ' + Quote(ADef.ColumnName) + ' TYPE ' + MapLogicalType(ADef.LogicalType, ADef.TypeArg, ADef.Precision, ADef.Scale));

    if ADef.NullabilityChanged then
    begin
      if ADef.NotNull then
        LParts.Add('ALTER COLUMN ' + Quote(ADef.ColumnName) + ' SET NOT NULL')
      else
        LParts.Add('ALTER COLUMN ' + Quote(ADef.ColumnName) + ' DROP NOT NULL');
    end;

    if ADef.DefaultDropped then
      LParts.Add('ALTER COLUMN ' + Quote(ADef.ColumnName) + ' DROP DEFAULT')
    else if ADef.DefaultSet then
      LParts.Add('ALTER COLUMN ' + Quote(ADef.ColumnName) + ' SET DEFAULT ' + GetLiteralValue(ADef.DefaultValue, ADef.LogicalType));

    if ADef.IdentityChanged then
    begin
      if ADef.IdentityScope = disByDefault then
        LParts.Add('ALTER COLUMN ' + Quote(ADef.ColumnName) + ' SET GENERATED BY DEFAULT')
      else
        LParts.Add('ALTER COLUMN ' + Quote(ADef.ColumnName) + ' SET GENERATED ALWAYS');
    end;

    if LParts.Count = 0 then
      raise EArgumentException.Create('DDL PostgreSQL: at least one change is required for ALTER COLUMN.');

    LParts.Delimiter := ',';
    LParts.QuoteChar := #0;
    Result := LBase + ' ' + LParts.DelimitedText;
  finally
    LParts.Free;
  end;
end;



function TFluentDDLSerializerPostgreSQL.CreateIndex(const ADef: IFluentDDLCreateIndexDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if ADef.IsUnique then
    Result := 'CREATE UNIQUE INDEX ' + Quote(ADef.IndexName) + ' ON ' + Quote(ADef.TableName) + ' (' + GetColumnNameList(ADef) + ')'
  else
    Result := 'CREATE INDEX ' + Quote(ADef.IndexName) + ' ON ' + Quote(ADef.TableName) + ' (' + GetColumnNameList(ADef) + ')';
end;

function TFluentDDLSerializerPostgreSQL.DropIndex(const ADef: IFluentDDLDropIndexDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if Trim(ADef.GetTableName) <> '' then
    raise ENotSupportedException.Create('DDL DROP INDEX: table name is not supported for PostgreSQL (DROP INDEX ... ON ...).');

  if ADef.GetConcurrently then
  begin
    if ADef.GetIfExists then
      Result := 'DROP INDEX CONCURRENTLY IF EXISTS ' + Quote(ADef.IndexName)
    else
      Result := 'DROP INDEX CONCURRENTLY ' + Quote(ADef.IndexName);
  end
  else if ADef.GetIfExists then
    Result := 'DROP INDEX IF EXISTS ' + Quote(ADef.IndexName)
  else
    Result := 'DROP INDEX ' + Quote(ADef.IndexName);
end;

function TFluentDDLSerializerPostgreSQL.TruncateTable(const ADef: IFluentDDLTruncateTableDef): string;
var
  LI: Integer;
begin
  if not Assigned(ADef) then
    Exit('');

  Result := 'TRUNCATE TABLE ';
  for LI := 0 to Length(ADef.TableNames) - 1 do
  begin
    if LI > 0 then Result := Result + ', ';
    Result := Result + Quote(ADef.TableNames[LI]);
  end;

  if ADef.RestartIdentity then
    Result := Result + ' RESTART IDENTITY'
  else if ADef.ContinueIdentity then
    Result := Result + ' CONTINUE IDENTITY';

  if ADef.Cascade then
    Result := Result + ' CASCADE';

  if ADef.PartitionName <> '' then
    raise ENotSupportedException.Create('DDL PostgreSQL: PARTITION clause is not supported for TRUNCATE.');
end;

function TFluentDDLSerializerPostgreSQL.CreateView(const ADef: IFluentDDLCreateViewDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if ADef.OrReplace then
    Result := 'CREATE OR REPLACE VIEW ' + Quote(ADef.ViewName) + ' AS ' + ADef.Query.AsString
  else
    Result := 'CREATE VIEW ' + Quote(ADef.ViewName) + ' AS ' + ADef.Query.AsString;
end;

function TFluentDDLSerializerPostgreSQL.DropView(const ADef: IFluentDDLDropViewDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if ADef.IfExists then
    Result := 'DROP VIEW IF EXISTS ' + Quote(ADef.ViewName)
  else
    Result := 'DROP VIEW ' + Quote(ADef.ViewName);
end;

function TFluentDDLSerializerPostgreSQL.CreateSequence(const ADef: IFluentDDLCreateSequenceDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  Result := 'CREATE SEQUENCE ' + Quote(ADef.SequenceName);
end;

function TFluentDDLSerializerPostgreSQL.DropSequence(const ADef: IFluentDDLDropSequenceDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if ADef.IfExists then
    Result := 'DROP SEQUENCE IF EXISTS ' + Quote(ADef.SequenceName)
  else
    Result := 'DROP SEQUENCE ' + Quote(ADef.SequenceName);
end;

function TFluentDDLSerializerPostgreSQL.AlterTableAddConstraint(const ADef: IFluentDDLAlterTableAddConstraintDef): string;
begin
  Result := inherited AlterTableAddConstraint(ADef);
end;

function TFluentDDLSerializerPostgreSQL.AlterTableDropConstraint(const ADef: IFluentDDLAlterTableDropConstraintDef): string;
begin
  Result := inherited AlterTableDropConstraint(ADef);
end;

function TFluentDDLSerializerPostgreSQL.CreateProcedure(const ADef: IFluentDDLProcedureDef): string;
begin
  if not Assigned(ADef) then
    Exit('');

  if ADef.OrReplace then
    Result := 'CREATE OR REPLACE PROCEDURE ' + Quote(ADef.ProcedureName)
  else
    Result := 'CREATE PROCEDURE ' + Quote(ADef.ProcedureName);

  Result := Result + '(' + ADef.Params + ') LANGUAGE plpgsql AS $$ ' + ADef.Body + ' $$';
end;

function TFluentDDLSerializerPostgreSQL.DropProcedure(const ADef: IFluentDDLDropProcedureDef): string;
begin
  if not Assigned(ADef) then
    Exit('');

  if ADef.IfExists then
    Result := 'DROP PROCEDURE IF EXISTS ' + Quote(ADef.ProcedureName)
  else
    Result := 'DROP PROCEDURE ' + Quote(ADef.ProcedureName);
end;

function TFluentDDLSerializerPostgreSQL.CreateTrigger(const ADef: IFluentDDLTriggerDef): string;
var
  LTime, LEvent: string;
begin
  if not Assigned(ADef) then
    Exit('');

  LTime := 'AFTER';
  if ADef.Time = ttBefore then LTime := 'BEFORE';

  case ADef.Event of
    teInsert: LEvent := 'INSERT';
    teUpdate: LEvent := 'UPDATE';
    teDelete: LEvent := 'DELETE';
  else
    LEvent := 'INSERT';
  end;

  Result := 'CREATE TRIGGER ' + Quote(ADef.TriggerName) + ' ' + LTime + ' ' + LEvent +
            ' ON ' + Quote(ADef.TableName) + ' FOR EACH ROW ' + ADef.Body;
end;

function TFluentDDLSerializerPostgreSQL.DropTrigger(const ADef: IFluentDDLDropTriggerDef): string;
begin
  if not Assigned(ADef) then
    Exit('');

  if ADef.IfExists then
    Result := 'DROP TRIGGER IF EXISTS ' + Quote(ADef.TriggerName) + ' ON ' + Quote(ADef.TableName)
  else
    Result := 'DROP TRIGGER ' + Quote(ADef.TriggerName) + ' ON ' + Quote(ADef.TableName);
end;

function TFluentDDLSerializerPostgreSQL.ManageTrigger(const ADef: IFluentDDLTriggerManagementDef): string;
begin
  if not Assigned(ADef) then
    Exit('');

  if ADef.Enabled then
    Result := 'ALTER TABLE ' + Quote(ADef.TableName) + ' ENABLE TRIGGER ' + Quote(ADef.TriggerName)
  else
    Result := 'ALTER TABLE ' + Quote(ADef.TableName) + ' DISABLE TRIGGER ' + Quote(ADef.TriggerName);
end;

function TFluentDDLSerializerPostgreSQL.CreateFunction(const ADef: IFluentDDLFunctionDef): string;
begin
  if not Assigned(ADef) then
    Exit('');

  if ADef.OrReplace then
    Result := 'CREATE OR REPLACE FUNCTION ' + Quote(ADef.FunctionName)
  else
    Result := 'CREATE FUNCTION ' + Quote(ADef.FunctionName);

  Result := Result + '(' + ADef.Params + ') RETURNS ' + ADef.Returns +
            ' LANGUAGE plpgsql AS $$ ' + ADef.Body + ' $$';
end;

function TFluentDDLSerializerPostgreSQL.DropFunction(const ADef: IFluentDDLDropFunctionDef): string;
begin
  if not Assigned(ADef) then
    Exit('');

  if ADef.IfExists then
    Result := 'DROP FUNCTION IF EXISTS ' + Quote(ADef.FunctionName)
  else
    Result := 'DROP FUNCTION ' + Quote(ADef.FunctionName);
end;

function TFluentDDLSerializerPostgreSQL.CreateSchema(const ADef: IFluentSQLSchemaDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  Result := 'CREATE SCHEMA ' + Quote(ADef.GetSchemaName);
end;

function TFluentDDLSerializerPostgreSQL.DropSchema(const ADef: IFluentSQLSchemaDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  Result := 'DROP SCHEMA ' + Quote(ADef.GetSchemaName);
end;

end.
