{
  ------------------------------------------------------------------------------
  FluentSQL
  Oracle DDL serialization driver.

  SPDX-License-Identifier: MIT
  Copyright (c) 2026 Ecosystem - Innovative Tools for Delphi Development

  Licensed under the MIT License.
  See the LICENSE file in the project root for full license information.
  ------------------------------------------------------------------------------
}

unit FluentSQL.DDL.Serialize.Oracle;

interface

{$ifdef fpc}
  {$mode delphi}{$H+}
{$endif}

uses
  SysUtils,
  FluentSQL.Interfaces,
  FluentSQL.DDL.SerializeAbstract;

type
  TFluentDDLSerializerOracle = class(TFluentDDLSerializeAbstract)
  protected
    function MapLogicalType(const AType: TDDLLogicalType; const AArg: Integer = 0;
      const APrecision: Integer = 0; const AScale: Integer = 0): string; override;
    function GetDialect: TFluentSQLDriver; override;
    function Quote(const AName: string): string; override;
    function GetComputedDefinition(const ACol: IFluentDDLColumn): string; override;
    function GetIdentityDefinition(const ACol: IFluentDDLColumn): string; override;
  public
    function CreateTable(const ADef: IFluentDDLTableDef): string; override;
    function DropTable(const ADef: IFluentDDLDropTableDef): string; override;
    function AlterTableAddColumn(const ADef: IFluentDDLAlterTableAddColumnDef): string; override;
    function AlterTableDropColumn(const ADef: IFluentDDLAlterTableDropColumnDef): string; override;
    function AlterTableRenameColumn(const ADef: IFluentDDLAlterTableRenameColumnDef): string; override;
    function AlterTableAlterColumn(const ADef: IFluentDDLAlterTableAlterColumnDef): string; override;
    function CreateIndex(const ADef: IFluentDDLCreateIndexDef): string; override;
    function DropIndex(const ADef: IFluentDDLDropIndexDef): string; override;
    function TruncateTable(const ADef: IFluentDDLTruncateTableDef): string; override;
    function CreateView(const ADef: IFluentDDLCreateViewDef): string; override;
    function DropView(const ADef: IFluentDDLDropViewDef): string; override;
  end;

implementation

{ TFluentDDLSerializerOracle }

function TFluentDDLSerializerOracle.GetDialect: TFluentSQLDriver;
begin
  Result := dbnOracle;
end;

function TFluentDDLSerializerOracle.Quote(const AName: string): string;
begin
  if (AName = '') or (AName.StartsWith('"')) then
    Exit(AName);
  Result := '"' + UpperCase(AName) + '"';
end;

function TFluentDDLSerializerOracle.GetComputedDefinition(const ACol: IFluentDDLColumn): string;
begin
  Result := '';
  if ACol.ComputedExpression <> '' then
    Result := ' GENERATED ALWAYS AS (' + ACol.ComputedExpression + ') VIRTUAL';
end;

function TFluentDDLSerializerOracle.GetIdentityDefinition(const ACol: IFluentDDLColumn): string;
begin
  Result := '';
  if ACol.IsIdentity then
  begin
    if ACol.IdentityScope = disByDefault then
      Result := ' GENERATED BY DEFAULT AS IDENTITY'
    else
      Result := ' GENERATED ALWAYS AS IDENTITY';
  end;
end;

function TFluentDDLSerializerOracle.MapLogicalType(const AType: TDDLLogicalType; const AArg: Integer;
  const APrecision: Integer; const AScale: Integer): string;
begin
  case AType of
    dltInteger:
      Result := 'NUMBER(10)';
    dltBigInt:
      Result := 'NUMBER(19)';
    dltVarChar:
      Result := 'VARCHAR2(' + IntToStr(AArg) + ')';
    dltBoolean:
      Result := 'NUMBER(1)';
    dltDate:
      Result := 'DATE';
    dltDateTime:
      Result := 'TIMESTAMP';
    dltLongText:
      Result := 'CLOB';
    dltBlob:
      Result := 'BLOB';
    dltGuid:
      Result := 'RAW(16)';
    dltNumeric: Result := MapNumeric('NUMBER', APrecision, AScale);
    dltDecimal: Result := MapNumeric('DECIMAL', APrecision, AScale);
  else
    raise ENotSupportedException.Create('DDL: unknown logical type');
  end;
end;

function TFluentDDLSerializerOracle.CreateTable(const ADef: IFluentDDLTableDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if ADef.GetColumnCount <= 0 then
    raise EArgumentException.Create('DDL: empty column list');

  Result := 'CREATE TABLE ' + Quote(ADef.TableName) + ' (' + GetColumnDefinitionList(ADef) + GetTableConstraintList(ADef) + ')';
end;

function TFluentDDLSerializerOracle.DropTable(const ADef: IFluentDDLDropTableDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if Trim(ADef.TableName) = '' then
    raise EArgumentException.Create('DDL: table name is required');

  Result := 'DROP TABLE ' + Quote(ADef.TableName);
end;

function TFluentDDLSerializerOracle.AlterTableAddColumn(const ADef: IFluentDDLAlterTableAddColumnDef): string;
begin
  if not Assigned(ADef) or not Assigned(ADef.Column) then
    Exit('');
  Result := 'ALTER TABLE ' + Quote(ADef.TableName) + ' ADD ' + GetColumnDefinition(ADef.Column);
end;

function TFluentDDLSerializerOracle.AlterTableDropColumn(const ADef: IFluentDDLAlterTableDropColumnDef): string;
begin
  if not Assigned(ADef) or (ADef.ColumnName = '') then
    Exit('');
  Result := 'ALTER TABLE ' + Quote(ADef.TableName) + ' DROP COLUMN ' + Quote(ADef.ColumnName);
end;

function TFluentDDLSerializerOracle.AlterTableRenameColumn(const ADef: IFluentDDLAlterTableRenameColumnDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  Result := 'ALTER TABLE ' + Quote(ADef.TableName) + ' RENAME COLUMN ' + Quote(ADef.OldColumnName) + ' TO ' + Quote(ADef.NewColumnName);
end;

function TFluentDDLSerializerOracle.AlterTableAlterColumn(const ADef: IFluentDDLAlterTableAlterColumnDef): string;
var
  LParts: string;
begin
  if not Assigned(ADef) then
    Exit('');

  LParts := Quote(ADef.ColumnName);
  if ADef.TypeChanged then
    LParts := LParts + ' ' + MapLogicalType(ADef.LogicalType, ADef.TypeArg, ADef.Precision, ADef.Scale);

  if ADef.NullabilityChanged then
  begin
    if ADef.NotNull then
      LParts := LParts + ' NOT NULL'
    else
      LParts := LParts + ' NULL';
  end;

  if ADef.IdentityChanged then
  begin
    if ADef.IdentityScope = disByDefault then
      LParts := LParts + ' GENERATED BY DEFAULT AS IDENTITY'
    else
      LParts := LParts + ' GENERATED ALWAYS AS IDENTITY';
  end;

  if (not ADef.TypeChanged) and (not ADef.NullabilityChanged) and (not ADef.IdentityChanged) then
    raise EArgumentException.Create('DDL Oracle: at least one change is required for ALTER COLUMN.');

  Result := 'ALTER TABLE ' + Quote(ADef.TableName) + ' MODIFY (' + LParts + ')';
end;

function TFluentDDLSerializerOracle.CreateIndex(const ADef: IFluentDDLCreateIndexDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if ADef.IsUnique then
    Result := 'CREATE UNIQUE INDEX ' + Quote(ADef.IndexName) + ' ON ' + Quote(ADef.TableName) + ' (' + GetColumnNameList(ADef) + ')'
  else
    Result := 'CREATE INDEX ' + Quote(ADef.IndexName) + ' ON ' + Quote(ADef.TableName) + ' (' + GetColumnNameList(ADef) + ')';
end;

function TFluentDDLSerializerOracle.DropIndex(const ADef: IFluentDDLDropIndexDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  Result := 'DROP INDEX ' + Quote(ADef.IndexName);
end;

function TFluentDDLSerializerOracle.TruncateTable(const ADef: IFluentDDLTruncateTableDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if Length(ADef.TableNames) > 1 then
    raise ENotSupportedException.Create('DDL Oracle: multiple tables in a single TRUNCATE are not supported.');
  if ADef.RestartIdentity or ADef.ContinueIdentity or ADef.Cascade or (ADef.PartitionName <> '') then
    raise ENotSupportedException.Create('DDL Oracle: advanced TRUNCATE options are not supported.');

  Result := 'TRUNCATE TABLE ' + Quote(ADef.TableName);
end;

function TFluentDDLSerializerOracle.CreateView(const ADef: IFluentDDLCreateViewDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  if ADef.OrReplace then
    Result := 'CREATE OR REPLACE VIEW ' + Quote(ADef.ViewName) + ' AS ' + ADef.Query.AsString
  else
    Result := 'CREATE VIEW ' + Quote(ADef.ViewName) + ' AS ' + ADef.Query.AsString;
end;

function TFluentDDLSerializerOracle.DropView(const ADef: IFluentDDLDropViewDef): string;
begin
  if not Assigned(ADef) then
    Exit('');
  Result := 'DROP VIEW ' + Quote(ADef.ViewName);
end;

end.
